language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx

install:
  - true

branches:
  only:
    - develop
    - master

jdk:
  - oraclejdk14
  
before_install:
  gradle wrapper
  
script:
  - ./gradlew -version
  - ./gradlew build --scan -s
  - ./graldew Test
