language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx

install:
  - true

script:
  - ./gradlew test   #lancia il task che prevede i test

before_install:
  - sudo apt update
  - sudo apt install openfx

branches:
  only:
    - develop
    - master
