language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx
  - windows

install:
  - true

branches:
  only:
    - develop
    - master

jdk:
  - oraclejdk14

script:
  - cd ./Trasporti116-117/
