language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx

install:
  - true

branches:
  only:
    - develop
    - master

jdk:
  - oraclejdk14

script:
  - Trasporti116-117/graldew Test
