language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx

install:
  - true

script:
  - ./gradlew test   #lancia il task che prevede i test

branches:
  only:
    - develop
    - master
