language: java

git:
  depth: false
  autocrlf: input

os:
  - linux
  - osx

install:
  - true

branches:
  only:
    - develop
    - master
    
before_install:
  - pwd
  - ls -la
  - cd Trasporti116-117
  - pwd
  - ls -la
  - ./graldew Test

jdk:
  - oraclejdk14

script:
 

