name: Java CI with Gradle

on:
  push:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Build with Gradle
      working-directory: ./Trasporti116-117
      run: ./gradlew check
