name: Java CI with Gradle

on:
  push:
    branches:
      - develop
      - master
  schedule:
    # il primo giorno di ogni mese
    - cron:  '* * 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu, windows, macos]
        java_version: [11, 14, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'adopt'
          check-latest: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./Trasporti116-117
        run: ./gradlew check
