name: Java CI with Gradle

on:
  push:
    branches:
      - develop
      - master
  schedule:
    # il primo giorno di ogni mese
    - cron:  '* * 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        java_version: [11, 14, 16]
  runs-on: [ubuntu, windows, macos]
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Build with Gradle
      working-directory: ./Trasporti116-117
      run: ./gradlew check
