name: Java CI with Gradle

on:
  push:
    branches:
      - develop
      - master
  schedule:
    # il primo giorno di ogni mese
    - cron:  '* * 1 * *'

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu, windows, macos]
        java_version: [11, 14, 16]
    runs-on: [ubuntu, windows, macos]
  steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./Trasporti116-117
      run: ./gradlew check
